import type { Metadata } from "next";
import { Geist, Geist_Mono,Inter } from "next/font/google";
import "./globals.css";
import "@ant-design/v5-patch-for-react-19";
import  'antd/dist/reset.css'
import AppProvider from "@/provider/AppProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Inter({
  subsets: ['latin'],
  weight: [ '200','300','400','500','600' ,'800' ,'900', '700'], // optional
  variable: '--font-roboto', // optional CSS variable
  display: 'swap', // recommended for better performance
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={roboto.className}>
      <body
        
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
